# Generated by Django 4.1.4 on 2023-01-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='host',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='words',
        ),
    ]
