# Generated by Django 4.1.4 on 2023-01-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
