# Generated by Django 4.1.4 on 2023-02-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='fix',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
