# Generated by Django 4.1.4 on 2023-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_post_options_rename_datetime_post_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userfile',
            field=models.FileField(blank=True, upload_to='imageuser/'),
        ),
    ]
