# Generated by Django 4.1.4 on 2023-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_post_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userfile',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='image/'),
        ),
    ]
