# Generated by Django 4.1.4 on 2023-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_post_userfile_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
