# Generated by Django 4.1.4 on 2023-02-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imageuser/%Y/%m/%d'),
        ),
    ]
