# Generated by Django 4.1.4 on 2023-02-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_post_filename_alter_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='filename',
        ),
        migrations.AddField(
            model_name='post',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='imageuser/%Y/%m/%d'),
        ),
    ]
