# Generated by Django 4.1.4 on 2023-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_remove_post_file_remove_post_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_user',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imageuser/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
