# Generated by Django 4.1.4 on 2023-02-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_remove_post_image_user_post_file_post_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='imageuser/%Y/%m/%d'),
        ),
    ]
