# Generated by Django 4.1.4 on 2023-02-16 20:08

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_alter_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filename',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imageuser/'),
        ),
    ]
