# Generated by Django 4.1.4 on 2023-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_remove_post_filename_post_img_alter_post_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='image-user/%Y/%m/%d/'),
        ),
    ]
