# Generated by Django 4.1.4 on 2023-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_alter_post_options_remove_post_img_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
