# Generated by Django 4.1.4 on 2023-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_post_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
