# Generated by Django 4.1.4 on 2023-02-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_post_url_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
